site_name: jobberRails
site_url: http://www.jobberrails.com
search_suggestions: '(e.g. "ajax", "designer, london", "php, chicago")'

# App email
from_email: from_sender@your-domain.com
support_email: support@your-domain.com
patrol_email: patrol-noreply@your-domain.com
require_email_activation: true
